-- 中国各省份旅游信息数据
-- 自动生成: 从 中国各省份旅游列表.md 文件转换而来
-- 包含: 34个省份 + 香港、澳门、台湾，共132个景点
-- 字段: 景点名称、所属省份、宣传词、宣传照片描述

DELETE FROM attractions;
DELETE FROM provinces;

-- ========== 省份数据 ==========
INSERT INTO provinces (id, name_zh, slug) VALUES
('sh', '上海市', '上海'),
('yn', '云南省', '云南'),
('nmg', '内蒙古自治区', '内蒙古'),
('bj', '北京市', '北京'),
('tw', '台湾省', '台湾'),
('jl', '吉林省', '吉林'),
('sc', '四川省', '四川'),
('tj', '天津市', '天津'),
('nx', '宁夏回族自治区', '宁夏回族'),
('ah', '安徽省', '安徽'),
('sd', '山东省', '山东'),
('sx2', '山西省', '山西'),
('gd', '广东省', '广东'),
('gx', '广西壮族自治区', '广西壮族'),
('xj', '新疆维吾尔自治区', '新疆维吾尔'),
('js', '江苏省', '江苏'),
('jx', '江西省', '江西'),
('heb', '河北省', '河北'),
('hen', '河南省', '河南'),
('zj', '浙江省', '浙江'),
('hain', '海南省', '海南'),
('hb', '湖北省', '湖北'),
('hn', '湖南省', '湖南'),
('am', '澳门特别行政区', '澳门'),
('gs', '甘肃省', '甘肃'),
('fj', '福建省', '福建'),
('xz', '西藏自治区', '西藏'),
('gz', '贵州省', '贵州'),
('ln', '辽宁省', '辽宁'),
('cq', '重庆市', '重庆'),
('sx', '陕西省', '陕西'),
('qh', '青海省', '青海'),
('hk', '香港特别行政区', '香港'),
('hlj', '黑龙江省', '黑龙江');

-- ========== 景点数据 ==========
INSERT INTO attractions (id, province_id, name_zh, promotion_text, image_url) VALUES
('1', 'sh', '上海迪士尼乐园', '奇幻童话城堡烟火秀 / 与玲娜贝儿互动', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Shanghai_Disney_Castle.jpg'),
('2', 'sh', '外滩', '万国建筑群与陆家嘴三件套同框', 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Shanghai_Bund.jpg'),
('3', 'sh', '豫园', '', 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Yu_Garden.jpg'),
('4', 'sh', '武康大楼', '', 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Wukang_Building.jpg'),
('5', 'yn', '丽江古城', '四方街油纸伞巷仰拍 / 大水车夜景', 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Lijiang_watertown.jpg'),
('6', 'yn', '大理洱海', 'S湾公路自行车与蓝色洱海 / 龙龛码头红杉日出', 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Erhai_lake.jpg'),
('7', 'yn', '西双版纳', '星光夜市全景航拍 / 傣装泼水节水花瞬间', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Xishuangbanna_landscape.jpg'),
('8', 'yn', '玉龙雪山', '冰川公园4680米石碑打卡照', 'https://upload.wikimedia.org/wikipedia/commons/0/06/Jade_Dragon_Snow_Mountain.jpg'),
('9', 'yn', '梅里雪山', '飞来寺观景台“日照金山”', 'https://upload.wikimedia.org/wikipedia/commons/1/16/Meili_Snow_Mountains.jpg'),
('10', 'nmg', '呼伦贝尔大草原', '', 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Hulun_Buir_grassland.jpg'),
('11', 'nmg', '额济纳胡杨林', '', 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Ejina_Poplar_Forest.jpg'),
('12', 'nmg', '阿尔山', '', 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Arshan_mountain.jpg'),
('13', 'bj', '故宫博物院', '太和殿中轴线全景 / 角楼日落倒影', 'https://upload.wikimedia.org/wikipedia/commons/2/28/Forbidden_City_Summer.jpg'),
('14', 'bj', '环球影城', '霍格沃茨城堡夜间灯光秀 / 小黄人乐园街拍', 'https://upload.wikimedia.org/wikipedia/commons/3/38/Universal_Studios_Beijing.jpg'),
('15', 'bj', '八达岭长城', '北四楼“好汉坡”绵延城墙秋色', 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Great_Wall_of_China_at_Badaling.jpg'),
('16', 'bj', '天安门广场', '', 'https://upload.wikimedia.org/wikipedia/commons/8/83/Tiananmen_Square.jpg'),
('17', 'bj', '颐和园', '十七孔桥“金光穿洞”（冬至前后）', 'https://upload.wikimedia.org/wikipedia/commons/1/10/Summer_Palace_17_Arch_Bridge.jpg'),
('18', 'tw', '日月潭', '', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Sun_Moon_Lake.jpg'),
('19', 'tw', '阿里山', '', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Alishan_Forest_Railway.jpg'),
('20', 'tw', '台北故宫博物院', '', 'https://upload.wikimedia.org/wikipedia/commons/1/1d/National_Palace_Museum.jpg'),
('21', 'tw', '垦丁', '', 'https://upload.wikimedia.org/wikipedia/commons/4/44/Kenting_beach.jpg'),
('22', 'jl', '长白山天池', '北坡天池开冰 / 冬季温泉煮鸡蛋冰雪两重天', 'https://upload.wikimedia.org/wikipedia/commons/7/75/Changbai_Mountain_Lake.jpg'),
('23', 'jl', '延吉', '民俗园“朝鲜族公主”写真的网红墙弹幕', 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Yanji_city.jpg'),
('24', 'sc', '九寨沟', '五花海“孔雀河道”全景 / 诺日朗瀑布冰瀑蓝冰', 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Five_Flower_Lake%2C_Jiuzhaigou.jpg'),
('25', 'sc', '成都大熊猫繁育研究基地', '熊猫“花花”正脸啃竹子 / 幼崽集体“摆烂”趴树', 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Giant_Panda_2004-03-17.jpg'),
('26', 'sc', '三星堆博物馆', '青铜大立人像特写 / 黄金面具正面', 'https://upload.wikimedia.org/wikipedia/commons/2/22/Sanxingdui_bronze_head.jpg'),
('27', 'sc', '稻城亚丁', '牛奶海与央迈勇雪山同框倒影', 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Mt_Yangmai_from_Yading.jpg'),
('28', 'sc', '峨眉山', '金顶十方普贤像＋云海＋日出', 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Golden_Summit_Emei_Mountain.jpg'),
('29', 'tj', '五大道', '海棠花掩映小洋楼街景', 'https://upload.wikimedia.org/wikipedia/commons/4/45/Five_Avenues_Tianjin.jpg'),
('30', 'tj', '天津之眼', '', 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Tianjin_Eye_ferris_wheel.jpg'),
('31', 'tj', '泰达航母主题公园', '', 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Tianjin_Aircraft_Carrier_Theme_Park.jpg'),
('32', 'nx', '沙坡头', '', 'https://upload.wikimedia.org/wikipedia/commons/5/54/Shapotou_desert.jpg'),
('33', 'nx', '镇北堡西部影城', '', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Zhenbeipu_Western_Film_Studio.jpg'),
('34', 'nx', '西夏陵', '', 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Western_Xia_Mausoleum.jpg'),
('35', 'ah', '黄山', '迎客松与天都峰 / 西海大峡谷观光缆车云海', 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Mount_Huangshan.jpg'),
('36', 'ah', '宏村', '月沼半月形倒影 / 南湖画桥', 'https://upload.wikimedia.org/wikipedia/commons/1/15/Hongcun_Ancient_Village.jpg'),
('37', 'ah', '西递', '', 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Xidi_Ancient_Village.jpg'),
('38', 'sd', '泰山', '玉皇顶“五岳独尊”石碑与日出 / 夜爬手电灯带', 'https://upload.wikimedia.org/wikipedia/commons/0/06/Mount_Tai.jpg'),
('39', 'sd', '青岛海滨', '栈桥海鸥成群 / 崂山渔村山海', 'https://upload.wikimedia.org/wikipedia/commons/4/42/Qingdao_coast.jpg'),
('40', 'sd', '淄博海月龙宫烧烤广场', '', 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Zibo_BBQ.jpg'),
('41', 'sd', '威海', '火炬八街直通大海下坡路 / 布鲁威斯号沉船', 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Weihai_city.jpg'),
('42', 'sx2', '云冈石窟', '第20窟露天大佛微笑 / 应县木塔八角麻燕绕飞', 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Yungang_Grottoes.jpg'),
('43', 'sx2', '平遥古城', '', 'https://upload.wikimedia.org/wikipedia/commons/5/50/Pingyao_Ancient_City.jpg'),
('44', 'sx2', '应县木塔', '', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Yingxian_Wooden_Pagoda.jpg'),
('45', 'sx2', '五台山', '', 'https://upload.wikimedia.org/wikipedia/commons/3/39/Mount_Wutai.jpg'),
('46', 'gd', '广州长隆旅游度假区', '鲸鲨馆超大落地水族箱剪影', 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Chimelong_Paradise.jpg'),
('47', 'gd', '珠海长隆海洋王国', '鲸鲨馆超大落地水族箱剪影', 'https://upload.wikimedia.org/wikipedia/commons/4/48/Chimelong_Ocean_Kingdom.jpg'),
('48', 'gd', '潮汕', '', 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Chaoshan_food.jpg'),
('49', 'gx', '桂林漓江/阳朔', '', 'https://upload.wikimedia.org/wikipedia/commons/3/35/Li_River_Guilin.jpg'),
('50', 'gx', '涠洲岛', '', 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Weizhou_Island.jpg'),
('51', 'gx', '柳州', '', 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Liuzhou_city.jpg'),
('52', 'xj', '喀纳斯', '禾木村晨雾木屋炊烟 / 月亮湾“大脚印”', 'https://upload.wikimedia.org/wikipedia/commons/1/10/Kanas_Lake.jpg'),
('53', 'xj', '赛里木湖', '冰推奇观 / 湖畔天鹅与雪山同框', 'https://upload.wikimedia.org/wikipedia/commons/9/90/Sayram_Lake.jpg'),
('54', 'xj', '独库公路', '盘山公路悬崖航拍 / 盛夏路边雪山背景', 'https://upload.wikimedia.org/wikipedia/commons/5/50/Duku_Highway.jpg'),
('55', 'xj', '那拉提草原', '“空中草原”养蜂女雕塑与冷杉林', 'https://upload.wikimedia.org/wikipedia/commons/4/40/Nalati_grassland.jpg'),
('56', 'xj', '天山天池', '', 'https://upload.wikimedia.org/wikipedia/commons/2/22/Tianshan_Tianchi.jpg'),
('57', 'js', '南京', '夫子庙泮池游船灯火', 'https://upload.wikimedia.org/wikipedia/commons/5/57/Nanjing_skyline.jpg'),
('58', 'js', '苏州', '拙政园借景北寺塔 / 留园框景', 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Suzhou_gardens.jpg'),
('59', 'js', '无锡拈花湾', '', 'https://upload.wikimedia.org/wikipedia/commons/4/49/Nianhuawan_scenic_area.jpg'),
('60', 'jx', '景德镇', '无语菩萨（沉思罗汉）表情包实拍', 'https://upload.wikimedia.org/wikipedia/commons/4/45/Jingdezhen_porcelain.jpg'),
('61', 'jx', '庐山', '', 'https://upload.wikimedia.org/wikipedia/commons/5/57/Lushan_Mountain.jpg'),
('62', 'jx', '望仙谷', '悬崖民宿夜景灯光如苍兰诀', 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Wangxian_Valley.jpg'),
('63', 'jx', '武功山', '', 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Wugong_Mountain.jpg'),
('64', 'heb', '阿那亚', '孤独图书馆极简海景 / 沙丘美术馆', 'https://upload.wikimedia.org/wikipedia/commons/5/56/Aranya_art_community.jpg'),
('65', 'heb', '承德避暑山庄', '', 'https://upload.wikimedia.org/wikipedia/commons/9/98/Mountain_Resort.jpg'),
('66', 'heb', '山海关', '', 'https://upload.wikimedia.org/wikipedia/commons/6/66/Shanhaiguan_gate.jpg'),
('67', 'hen', '老君山', '金顶雪后远眺如天宫 / 十里画屏云海', 'https://upload.wikimedia.org/wikipedia/commons/3/30/Laojun_Mountain.jpg'),
('68', 'hen', '只有河南·戏剧幻城', '百亩麦田与夯土墙 / 椅阵剧场', 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Henan_Theater.jpg'),
('69', 'hen', '龙门石窟', '', 'https://upload.wikimedia.org/wikipedia/commons/2/28/Longmen_Grottoes.jpg'),
('70', 'hen', '少林寺', '', 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Shaolin_Temple.jpg'),
('71', 'zj', '杭州西湖', '曲院风荷“长桥”雷峰塔夕照 / 断桥残雪', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/West_Lake_Hangzhou.jpg'),
('72', 'zj', '横店影视城', '明清宫苑“剧组拍摄现场”穿越照', 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Hengdian_World_Studios.jpg'),
('73', 'zj', '普陀山', '南海观音立像仰拍 / 不肯去观音院海浪', 'https://upload.wikimedia.org/wikipedia/commons/2/27/Putuo_Mountain.jpg'),
('74', 'zj', '乌镇', '西栅夜景“小桥流水”船影 / 水上集市', 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Wuzhen_Ancient_Town.jpg'),
('75', 'hain', '三亚', '玻璃海“情人桥”航拍', 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Sanya_beach.jpg'),
('76', 'hain', '万宁', '日月湾冲浪“浪人”抓拍 / 海边椰林公路', 'https://upload.wikimedia.org/wikipedia/commons/9/95/Wanning_beach.jpg'),
('77', 'hain', '海口', '', 'https://upload.wikimedia.org/wikipedia/commons/1/14/Haikou_city.jpg'),
('78', 'hb', '恩施大峡谷', '', 'https://upload.wikimedia.org/wikipedia/commons/1/15/Enshi_Grand_Canyon.jpg'),
('79', 'hb', '武汉', '樱花园五重塔樱花吹雪', 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Wuhan_skyline.jpg'),
('80', 'hb', '武当山', '', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Wudang_Mountains.jpg'),
('81', 'hn', '张家界武陵源', '袁家界“哈利路亚悬浮山” / 天门洞999级阶梯', 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Zhangjiajie_National_Forest_Park.jpg'),
('82', 'hn', '长沙', '毛泽东青年雕像正面昂首', 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Changsha_night.jpg'),
('83', 'hn', '凤凰古城', '沱江跳岩与吊脚楼夜景 / 翠翠渡船', 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Phoenix_Ancient_Town.jpg'),
('84', 'am', '大三巴牌坊', '', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Ruins_of_St._Paul%27s_Macau.jpg'),
('85', 'am', '威尼斯人/伦敦人度假区', '', 'https://upload.wikimedia.org/wikipedia/commons/4/47/The_Venetian_Macao.jpg'),
('86', 'am', '澳门旅游塔', '', 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Macau_Tower.jpg'),
('87', 'gs', '敦煌莫高窟', '九层楼正面 / 复制洞窟壁画', 'https://upload.wikimedia.org/wikipedia/commons/6/66/Mogao_Caves_Dunhuang.jpg'),
('88', 'gs', '鸣沙山月牙泉', '万人星空演唱会手机灯海 / 骆驼红绿灯', 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Mingsha_Mountain_and_Crescent_Lake.jpg'),
('89', 'gs', '张掖七彩丹霞', '七彩丹霞“五花肉”深秋热气球', 'https://upload.wikimedia.org/wikipedia/commons/1/15/Zhangye_Danxia.jpg'),
('90', 'fj', '鼓浪屿', '日光岩俯拍红屋顶 / 最美转角“晴天墙”', 'https://upload.wikimedia.org/wikipedia/commons/0/07/Gulangyu_Island.jpg'),
('91', 'fj', '武夷山', '', 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Wuyi_Mountains.jpg'),
('92', 'fj', '泉州古城', '开元寺双塔与西街同框', 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Quanzhou_ancient_city.jpg'),
('93', 'xz', '布达拉宫', '药王山50元人民币同视角 / 倒影池夜景', 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Potala_Palace.jpg'),
('94', 'xz', '珠穆朗玛峰大本营', '', 'https://upload.wikimedia.org/wikipedia/commons/1/10/Mount_Everest.jpg'),
('95', 'xz', '纳木错', '', 'https://upload.wikimedia.org/wikipedia/commons/4/40/Namtso_Lake.jpg'),
('96', 'xz', '大昭寺', '', 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Jokhang_Temple.jpg'),
('97', 'gz', '黄果树瀑布', '水帘洞内穿瀑透视', 'https://upload.wikimedia.org/wikipedia/commons/7/72/Huangguoshu_Waterfall.jpg'),
('98', 'gz', '西江千户苗寨', '观景台万家灯火夜景', 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Xijiang_Miao_Village.jpg'),
('99', 'gz', '荔波小七孔', '', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Libo_Small_Seven_Arch.jpg'),
('100', 'gz', '梵净山', '', 'https://upload.wikimedia.org/wikipedia/commons/5/56/Fanjing_Mountain.jpg'),
('101', 'ln', '大连', '星海湾跨海大桥平流雾 / 滨海路傅家庄', 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Dalian_beach.jpg'),
('102', 'ln', '沈阳故宫', '', 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Shenyang_Imperial_Palace.jpg'),
('103', 'ln', '丹东', '', 'https://upload.wikimedia.org/wikipedia/commons/1/17/Dandong_city.jpg'),
('104', 'cq', '洪崖洞', '千厮门大桥视角的“千与千寻”夜景', 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Hongya_Cave.jpg'),
('105', 'cq', '李子坝轻轨穿楼', '仰拍轻轨穿楼瞬间', 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Liziba_Monorail_Station.jpg'),
('106', 'cq', '磁器口', '', 'https://upload.wikimedia.org/wikipedia/commons/5/56/Ciqikou_Ancient_Town.jpg'),
('107', 'sx', '秦始皇兵马俑博物馆', '一号坑全景阵列 / 跪射俑背面“陕西地图”鞋底', 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Terracotta_Army.jpg'),
('108', 'sx', '大唐不夜城', '“盛唐密盒”互动抓拍 / 不倒翁小姐姐牵手瞬间', 'https://upload.wikimedia.org/wikipedia/commons/7/76/Tang_West_Market.jpg'),
('109', 'sx', '陕西历史博物馆', '', 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Shaanxi_History_Museum.jpg'),
('110', 'sx', '华山长空栈道', '长空栈道绝壁行走 / 下棋亭云海', 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Mount_Hua.jpg'),
('111', 'qh', '青海湖', '', 'https://upload.wikimedia.org/wikipedia/commons/8/86/Qinghai_Lake.jpg'),
('112', 'qh', '茶卡盐湖', '天空之镜红裙倒影小火车', 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Chaka_Salt_Lake.jpg'),
('113', 'qh', '察尔汗盐湖', '', 'https://upload.wikimedia.org/wikipedia/commons/2/27/Chalhans_Salt_Lake.jpg'),
('114', 'hk', '香港迪士尼乐园', '', 'https://upload.wikimedia.org/wikipedia/commons/3/38/Hong_Kong_Disneyland_Castle.jpg'),
('115', 'hk', '维多利亚港星光大道', '', 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Victoria_Harbour_Hong_Kong.jpg'),
('116', 'hk', '太平山顶', '', 'https://upload.wikimedia.org/wikipedia/commons/6/6f/The_Peak_Hong_Kong.jpg'),
('117', 'hlj', '哈尔滨冰雪大世界', '主塔“冰雪之冠”夜景全景 / 雪花摩天轮', 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Harbin_Ice_Festival.jpg'),
('118', 'hlj', '索菲亚大教堂广场', '教堂前“人造月亮”升起 / 大雪纷飞异域风', 'https://upload.wikimedia.org/wikipedia/commons/6/63/Harbin_Cathedral.jpg'),
('119', 'hlj', '雪乡', '雪蘑菇木屋夜景灯光 / 栈道俯拍童话世界', 'https://upload.wikimedia.org/wikipedia/commons/8/83/Wuling_Snow_Town.jpg');
